// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4LwaIwU2-BpprUgselxTuXrDwVT3tEJs',
    appId: '1:97464491610:web:1548f0c666e060dbdd4263',
    messagingSenderId: '97464491610',
    projectId: 'gembala-kecil',
    authDomain: 'gembala-kecil.firebaseapp.com',
    storageBucket: 'gembala-kecil.firebasestorage.app',
    measurementId: 'G-K5TFJCH12Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATEJGEh-CCtdzCSGk35FOYzZwWDvgOp54',
    appId: '1:97464491610:android:7a29c3661c579ac6dd4263',
    messagingSenderId: '97464491610',
    projectId: 'gembala-kecil',
    storageBucket: 'gembala-kecil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_a8nDg9KeFmgWXhH9Vo_OyDL2VHBV0bI',
    appId: '1:97464491610:ios:eaafa8edb5cd3d26dd4263',
    messagingSenderId: '97464491610',
    projectId: 'gembala-kecil',
    storageBucket: 'gembala-kecil.firebasestorage.app',
    iosBundleId: 'com.gembalakecil.gembalaKecil',
  );
}
